### ISSUE TITLE
BBB Hardware kernel > 3.8

### ISSUE THREAD

**Issue by davehun** [node-red/node-red-nodes#156]
using the latest debian (jessie) the BBB module doesn't work
bonscript is n't installed and doesn't work due to kernel changes.
ocatalbonescript is currently WIP
https://github.com/theoctal/octalbonescript/issues/41
but event the current master doesn't quite work due to API changes

**Comment by dceejay** [comment]
Yes. agreed. As the octalbonescript guys are actively working a fix we will need to make their dependancy mandatory to this node, and update the API. Happy to accept a PR for this (as per Contribution Guidelines - https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md )

**Comment by dceejay** [comment]
could be a slightly tricky one... the octalbonescript fixes will then only work on 4.1 kernel - so will break all previous. So I'm not going to rush to fix this until it gets more stable.

**Comment by dceejay** [comment]
Ok - theoctal have updated octalbonescript so we can now pre-req it for Jessie... This will mean you will need to specify which version of this node you require for older Debian versions...  but will update instructions and README to suit...  I won't post the fix for a few days while I test it a bit first.
