### ISSUE TITLE
[emoncms] buffer results when emoncms is not available

### ISSUE THREAD

**Issue by arthurlutz** [node-red/node-red-nodes#197]
When using the output node of emoncms, the node can be occasionally unreachable (receiving site down or network of the node-red server down) it would be awesome if node-red could store the data to send it when the server or network becomes reachable again. 

Is there another node for this kind of behaviour ? Should it be a behaviour in node-red-emoncms ?

**Comment by dceejay** [comment]
Hi ,
in general we prefer ideas and discussions for new features to be held on the Google group rather than raised as issues.

There is currently no built in way to do this, but there are plenty of ways to store data, detect network connectivity, and fire the existing node, in some way.

Closing as not an issue with the existing node.
