### ISSUE TITLE
Email node crashes

### ISSUE THREAD

**Issue by snaik17** [node-red/node-red-nodes#210]
We have been using Email node in node-red and everything  was working perfectly .
Last week onwards , things just stopped working.

We noticed that earlier msg.object would also have fields like From , To fields etc.. but now we only see msg.payload with email content only.

Also the application crashed  frequently.
Is there a way to get older  stable version ?

**Comment by dceejay** [comment]
What did you "upgrade" - the whole of Node-RED ? or just the nodes ?
is the payload "almost" ok - ie is the content the content of the email- - ie partially working - just the extra fields missing ? or totally broken ?
What platform ? OS ? Which version of node.js and npm ? (the top of the console log will print out most of this info)

you can use npm install @ syntax to choose which version to install.. but it depends slightly on where the node is currently installed where you need to run the command to get it into the correct place.

**Comment by snaik17** [comment]
We are using Bluemix and node-red boiler plate application .
We have added email node to start with which captures emails and then stores this in Cloudant DB .

Earlier msg.object would have the To, From, Topic , Date  etc in addition to email content
But now it just shows message content only and these other fields are not shown.

**Comment by nkolban** [comment]
Howdy snaik17,
Looking at the source of the email nodes, I see that the email message received from the email server is parsed by employing a package called "mailparser" ... see:

https://www.npmjs.com/package/mailparser

I also see that it is now at version 0.6.0 while the Node-RED package for the email node forces it to be a previous release.  This may be an issue.  What I would suggest is that we setup a Node-RED environment that is off Bluemix (so that we can debug it) and connect it to your specific email server and do some tracing.    It looks like the parsing of an email body is not working correctly.

At a high level, what the email processing node does is poll the email server.  Email servers have two protocols ... IMAP and POP3 .. and depending on which protocol is chosen, different techniques are used to retrieve the email content.   Once the email is received, it is then passed into mailparser for processing.  So either we are not retrieving the email from the EMail server correctly (i.e. node-imap package) or the email isn't parsing correctly (i.e. mailparser package).

What we would need to do is edit the 61-email.js Node-RED file which contains the implementation of the email node and instrument it with debug statements to see what data we have at the relevant retrieval and parse points.  Once we see what we have there, that will allow us to delve deeper into that particular area.

Do you have the skills to perform those tasks?

**Comment by dceejay** [comment]
Neil, (et al),
the mailparser only seems to handle basic forms.... unfortunately multipart mime wrappers around email seem to be of many levels, and they are not handled at all well... I have had a go a bodging in a simple parser to try to cope with the basic cases of no wrapper, and single plain/html wrapper and a simple wrapper with attachments (even this then does not then provide subject... but hey)... 
To do it properly will need a recursive search, but there seem to be lots of exceptions to the rules... so I have no idea if it's possible...   Anyone who fancies a go is most welcome... :-)
