### ISSUE TITLE
wemo node crashes node-red sometimes

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#241]
14 Oct 17:07:52 - [red] Uncaught Exception:
14 Oct 17:07:52 - TypeError: Cannot read property 'addMembership' of null
    at addMembership [as _onTimeout](/home/andysc/.node-red/node_modules/node-red-node-wemo/node_modules/node-ssdp/lib/index.js:183:18)
    at Timer.listOnTimeout (timers.js:92:15)

I think it was when I had been connected to a network, then later wasn't.
Node-RED 0.15.0

**Comment by hardillb** [comment]
If you disconnect the network with node-red running, I'm not really surprised it now fails to find things that where on that network.

I'm re adding the error as you've not marked it as code so it's lost a lot of useful information.

```
14 Oct 17:07:52 - [red] Uncaught Exception:
14 Oct 17:07:52 - TypeError: Cannot read property 'addMembership' of null
    at addMembership [as _onTimeout] (/home/andysc/.node-red/node_modules/node-red-node-wemo/node_modules/node-ssdp/lib/index.js:183:18)
    at Timer.listOnTimeout (timers.js:92:15)

```

This error is coming from deep in the ssdp node that does the discovery for the WeMo devices. It looks to be failing to add a multicast group to the open socket it needs because there are no valid network adapters currently present.

It's failing in a timer that the ssdp node starts so I don't see any way to fix this

**Comment by andysc** [comment]
could we ask the ssdp folks?

**Comment by andysc** [comment]
worth mentioning that I'm not actually using a wemo node in my flow... so it's doing this with the node just sitting in the palette. Can you do anything to render it inactive until I use it in a flow?

**Comment by dceejay** [comment]
if you're using the node - you can now use the palette manager in version 0.15 to disable them.

**Comment by knolleary** [comment]
Have we raised an issue against the upstream project? Never going to be resolved otherwise.

**Comment by openSoftMan** [comment]
Should this issue have been raised upstream here [node-ssdp](https://github.com/diversario/node-ssdp) instead of [node-red-contrib-ssdp-discover](https://github.com/efa2000/node-red-contrib-ssdp-discover/issues)?

I picked up a few wemo outlets and would like to add them to node-red, but I don't want it crashing if network adapter goes down.

Is this still an issue?
Thanks all!

**Comment by hardillb** [comment]
Upstream bug fixed, will be included in next release of the node-red-node-wemo.

**Comment by dceejay** [comment]
@hardillb closeable now node released ?

**Comment by hardillb** [comment]
Ask @andysc

**Comment by andysc** [comment]
will try it this week

**Comment by hardillb** [comment]
Closing this as it's been 4+ years....
