### ISSUE TITLE
TI sensorTag - Set executable by non-root user

### ISSUE THREAD

**Issue by SeanStayn** [node-red/node-red-nodes#373]
Hey,

I'm new with PI and Raspbian. What is meaning with 'which node' in the following line? Where can I find the right node red node?

`sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)`

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.


 - The command \`which node\` returns the full path to the `node` executable.
 - `eval readlink -f` takes that path and resolves it to its original file in the case of a symlink
 - `sudo setcap cap_net_raw+eip` then sets a special permission on the original node file needed for `node` to access the device without using `root` permissions.


Thanks!
