### ISSUE TITLE
Long deploy time & buffer length of delay node

### ISSUE THREAD

**Issue by kangskii** [node-red/node-red-nodes#390]
Hello,

I am now developing a relatively complex project with node-red upon an embedded platform. The project includes many dashboard nodes. Every time I deploy the flow, it will require about 1 minute. 
Q1: Could you please tell how to accelerate the deploy process ?

The second question is the buffer length of the delay node. The followed is the warning info.
[warn] [delay:9a7ac0f7.9bf3c]  buffer exceeded 1000 messages

Q2: Can we configure the buffer length ?

thanks.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
