### ISSUE TITLE
arduino firmata add support for INPUT-PULLUP mode

### ISSUE THREAD

**Issue by fcasarsa** [node-red/node-red-nodes#455]
While using arduino firmata flow i noticed lot of spurious events switching an input from low to high and viceversa. It would be useful to add digital input pullup 0x0B mode, it is already present in firmata module, but it needs to be added in the node-red-node-arduino flow.

Thank-you.

**Comment by knolleary** [comment]
Hi,

please take a note of the message you were shown before opening the issue:

If your issue is:
  - a general 'how-to' type question,
  - a feature request or suggestion for a change,
  - or problems with 3rd party (`node-red-contrib-`) nodes

please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack), or ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

Thanks!

**Comment by dceejay** [comment]
(but yes - will look at adding it)

**Comment by dceejay** [comment]
Thanks for pointing this out.. .Now Added.
