### ISSUE TITLE
Deprecated packages mailparser, mailcomposer and nodemailer

### ISSUE THREAD

**Issue by MartinMuzatko** [node-red/node-red-nodes#456]
### Which node are you reporting an issue on?

`node-red-node-email`

### What are the steps to reproduce?

`npm install`

### What happens?

```
npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support
for newer bcrypt hashes
npm WARN deprecated i18next-client@1.10.3: you can use npm install i18next from version 2.0.0
npm WARN deprecated mailparser@0.6.2: This project is unmaintained
npm WARN deprecated nodemailer@1.11.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated delayed@1.0.1: no longer maintained
npm WARN deprecated mimelib@0.3.1: This project is unmaintained
npm WARN deprecated mailcomposer@2.1.0: This project is unmaintained
npm WARN deprecated buildmail@2.0.0: This project is unmaintained
```

There is https://www.npmjs.com/package/mailparser2 which replaces https://www.npmjs.com/package/mailparser

I am not sure if all the other libraries have maintained or newer libraries. 

### What do you expect to happen?

no warnings

### Please tell us about your environment:

- [x] Node-RED version: 0.18.7
- [x] node.js version: 8.9.1
- [x] npm version: 6.0.1
- [x] Platform/OS: Debian Wheezy
- [ ] Browser: not relevant for cli

**Comment by dceejay** [comment]
Thanks for reporting, but it's already been fixed in the actual repo - https://github.com/node-red/node-red-nodes/tree/master/social/email

We haven't updated the core package.json yet as a major bump in a dependency ought to cause us a major update also... Secondly the newer versions don't work on node 4.x - which although out of service is still the one shipped with Debian Stretch on Pi. We can't swap to the new one until we drop node.4.x and that will need us to release a new version... which may be soon... but may not that soon as dropping  a version does have other reverberations.

**Comment by MartinMuzatko** [comment]
Okay. thank you very much :) 
I will close this issue then.
