### ISSUE TITLE
Add support for images in pushover node

### ISSUE THREAD

**Issue by tve** [node-red/node-red-nodes#458]
### Which node are you reporting an issue on?

node-red-node-pushover

### What are the steps to reproduce?

Please add support for pushing images. Perhaps see https://github.com/RayPS/node-red-contrib-pushover ?

**Comment by knolleary** [comment]
For the issue template you were shown when raising:

If your issue is:
  - a general 'how-to' type question,
  - *a feature request or suggestion for a change*,
  - or problems with 3rd party (`node-red-contrib-`) nodes

please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

**Comment by knolleary** [comment]
If there is a contrib node that already provides this functionality then why not use that one?

**Comment by tve** [comment]
I guess so. I was disappointed that the built-in node I was using doesn't support the newer features. Dunno what your policy is, perhaps it's "built-in nodes provide minimal functionality, always look first for a good contrib node"?

**Comment by dceejay** [comment]
Our policy is to encourage people to offer pull requests for enhancements to nodes rather than fork them.. But we can't and won't stop them forking if they wish to. We do try to maintain the non-core nodes, but don't use them every day, so rely on the community to offer updates.

**Comment by dceejay** [comment]
html support was recently added - does that help cover this ?

**Comment by tve** [comment]
Implemented in #509, thanks!
