### ISSUE TITLE
SQLite - Add support for multiple queries/statements in msg.topic

### ISSUE THREAD

**Issue by tmdoit** [node-red/node-red-nodes#465]
Feature Request

**Comment by knolleary** [comment]
Hi,

did you read the issue template you were shown when you opened this issue?

This issue tracker is for problems with the extra nodes maintained by the Node-RED project.

If your issue is:
  - a general 'how-to' type question,
  - a feature request or suggestion for a change,
  - or problems with 3rd party (`node-red-contrib-`) nodes

please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack), or ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

That way the whole Node-RED user community can help, rather than rely on the core development team.
