### ISSUE TITLE
Request "callback" parameter

### ISSUE THREAD

**Issue by redlegoman** [node-red/node-red-nodes#625]
As title. I'd like to be able to send a URL in the callback Pushover API parameter. See here:
[https://pushover.net/api/receipts](url)

**Comment by dceejay** [comment]
As per the Issue form you managed to delete - we prefer requests for new functionality to be discussed via either slack or the discourse forum rather than just being an issue for the core developers.

We are happy to consider a Pull Request for this if you like - but as it's not a node I use day to day I'm not sure when I may get a chance to look at this myself.

**Comment by redlegoman** [comment]
Oops. Sorry.

**Comment by dceejay** [comment]
No worries - I'll leave this open as a reminder to look at it.

**Comment by brianmangan** [comment]
@dceejay I just put in a pull request so solve this issue #830 

hope it helps.

**Comment by dceejay** [comment]
Will close this - pending #832
