### ISSUE TITLE
node-red-node-mysql not properly disconnecting on loss of internet

### ISSUE THREAD

**Issue by AverageWeeaboo** [node-red/node-red-nodes#634]
The issue I am having is that the "connection" state is not being updated on internet downtime
### Which node are you reporting an issue on?
Node-red-node-mysql
### What are the steps to reproduce?
Start node-red with a wifi/internet connection and a properly configured mysql node that is for example "SELECT * FROM TableName". The next step is to disconnect the internet/wifi from the device running node-red. The mysql server I am connecting to is not local (its hosted on AWS).
### What happens?
The mysql node remains in the connected state and the resulting payload (and all future payloads) is not sent because there is no internet anymore but no error is sent. 
### What do you expect to happen?
What should happen is that the mysql node, when a message is sent, should error saying no connection like it normally does when node-red is started with no internet connection.
### Please tell us about your environment:
I am running node-red as a service in Raspbian on a raspberry Pi 3b+
- [ ] Node-RED version:
1.0.3
- [ ] node.js version:
10.15.2
- [ ] npm version:
6.14.0
- [ ] Platform/OS:
Raspbian Buster (10)
- [ ] Browser:
Chromium

**Comment by AverageWeeaboo** [comment]
I found an additional issue that's being created from this problem which I originally thought was my fault but I realized why its occurring:
When the msg object reaches the mysql node that appears connected but the internet is disconnected, the object does not get processed but instead gets placed in a queue to be processed (or something like that). When the internet is reconnected, the messages can be processed by the mysql node so all the ones sent while disconnected are then processed at once. This is causing me to get a duplicate primary key error on insertion because I am expecting only the messages while connected to the internet to be processed/kept while the rest are disposed of.

**Comment by dceejay** [comment]
If you just unplug then often the PC itself won't know that the connection has gone away until the query packet times out which can take 30 secs or so, as the underlying TCP connection doesn't fail right away. There was a case where this was not being shown in the status (just fixed in 0.0.21 - which now shows ETIMEOUT error once that timer has timed out). It will try to buffer any queries - this is built into the underlying library - and it will then retry them if the connection does come back. However if the breakage is too long, then the connection will error and it will then try to reconnect - at which point the client will reject any incoming messages until reconnected.

closed by 705dd1ffc11ab1101007df08474b50a4541db261
