### ISSUE TITLE
Change in host FQDN for one mysql node changes host FQDN all other mysql nodes in flow

### ISSUE THREAD

**Issue by baqwas** [node-red/node-red-nodes#635]
### Which node are you reporting an issue on?
**mysql**

### What are the steps to reproduce?
1. Insert two **mysql** nodes into flow
2. Update host FQDN in in 1st **mysql** node
3. Host FQDN in 2nd **mysql** node changes without user intervention
4. Unable to use two different MySQL/MariaDB servers in flow

### What happens?
* Changing the FQDN in any one **mysql** node, changes the FQDN in all existing **mysql** nodes in the flow.
* Dragging/dropping a new **mysql** node into flow seems to have its host value preset. Is this intentional? But then cannot change the host value owing to the reported issue.

### What do you expect to happen
I expect to be able to use different host database servers in the same flow. My use case is:
* Use primary host for INSERT operations
* Deploy database replication (one-way from primary to secondary)
* Use secondary host for SELECT operations

### Please tell us about your environment:

- [ ] Node-RED version: v0.20.7
- [ ] node.js version: v10.19.0
- [ ] npm version: v6.13.4
- [ ] Platform/OS: RPi Buster (with all applicable updates/upgrades applied)
- [ ] Browser: Firefox v74.6 (64-bit) running on Ubuntu 19.10

I don't know how long I have had this issue but some long running queries alerted me to this issue. I am a _newbie_ when it comes to Node-RED; I apologize in advance for raising an issue instead of reading the manual. The success of my database replication must have prevented me from realizing the underlying issue earlier. Since replication was working (validated external to N-R), I automatically assumed that the **mysql** node was connecting to the right database server since the expected data was being returned. It is only now that I realize that the second **mysql** node was connected to the same instance as the first **mysql** node!

Kind regards.

**Comment by hardillb** [comment]
This working as intended.

The mysql nodes use a pattern called a config node to hold the connection details (and to pool the actual connection to database pointed to by those details).

When you configured your first mysql node you will have selected the "Add new MYSQL Database.." option from the drop down

![Screenshot from 2020-03-14 07-14-01](https://user-images.githubusercontent.com/1800845/76677209-8b668000-65c3-11ea-8e66-6ea1827ac615.png)

Then filled in the details about that connection

![Screenshot from 2020-03-14 07-16-19](https://user-images.githubusercontent.com/1800845/76677232-c36dc300-65c3-11ea-90c5-7a9f7d7a26bf.png)

When you dragged a new node onto to the canvas, it will have been pre-populated with the config node from the first mysql node (because most of the time people are working with one database)

![Screenshot from 2020-03-14 07-18-29](https://user-images.githubusercontent.com/1800845/76677251-0c257c00-65c4-11ea-8a91-0f8711177349.png)

If you click on the pencil button this will edit the config node (which is currently shared between the 2 mysql nodes you have in use). If you want to have a separate config for the new mysql node then you need to click on the drop down at the end of that database input and select "Add new MYSQL Database.." again.

Now I will admit that the config nodes only use the database field to name themselves so if the only difference between 2 config nodes is the hostname then they are hard to tell apart, so we should probably have the label include the hostname as well.

**Comment by dceejay** [comment]
We typically haven't done this for other similar node - eg MQTT node, http request node - as adding the FDQN to the labels would make each node somewhat large.

**Comment by dceejay** [comment]
published as version 0.0.20
