### ISSUE TITLE
No Debug Output From Wemo Input Node

### ISSUE THREAD

**Issue by damiene77** [node-red/node-red-nodes#641]
**Which node are you reporting an issue on?**
node-red-node-wemo 0.1.16 (also tried older versions)

**What are the steps to reproduce?**
Added Wemo input node and attached to debug node.
Successfully changed state on Wemo device (Turn On and Off A Wemo Socket)

**What happens?**
1. Deploy Flow
2. Wemo input node status is 'found' (green light)
3. No output in debug window when operating the socket (switching on and off)

Note: The Wemo Out and Wemo Lookup Nodes work as intended.

**What do you expect to happen?**
Message to be returned in the debug window when a change occurs in the specified wemo device via the wemo input node

**Please tell us about your environment:**

- [ ] Node-RED version: 1.0.4
- [ ] node.js version: 12.16.1
- [ ] npm version: 6.14.4
- [ ] Platform/OS: Linux 4.19.66-v7l+ | Raspbian Linux 10 (Raspberry PI)
- [ ] Browser: Chrome (mostly)

**Comment by hardillb** [comment]
What type of device did you configure the node with?

**Comment by damiene77** [comment]
It is a Wemo Switch Smart Plug
Firmware: WeMo_WW_2.00.11408.PVT-OWRT-SNS
Hardware: V1

Not sure if links are allowed but this is it:
https://www.amazon.com/WeMo-Switch-Smart-Works-Alexa/dp/B00BB2MMNE/ref=sr_1_11?keywords=wemo+insight&qid=1585574265&sr=8-11

When configuring the node it comes up as a "socket" in device type automatically.

I have also tried an Wemo Insight which comes up as "socket" in device type as well.  I had the same results with it.

**Comment by hardillb** [comment]
OK, I have both of those devices and they are working fine for me (all be it the deployed instance is running a slightly older build).

I do have a pending update to take us to 0.1.17 you can try that here: https://www.hardill.me.uk/node-red-node-wemo-0.1.17-beta.0.tgz

You can install by running `npm install https://www.hardill.me.uk/node-red-node-wemo-0.1.17-beta.0.tgz` in you node-red userdir.

Please make sure you check the node-red logs while it's running. You should see on/off messages for the normal socket, and you get some power usages data as well with the insight.

I will update my local instance as well and have a look.

**Comment by hardillb** [comment]
OK, I'm now running with the 0.1.17-beta and it's still all working.

**Comment by damiene77** [comment]
I upgraded to the beta and still had the same issues, however, I think I may have narrowed down the issue but will need to confirm.  

It appears that somehow there was a conflict when securing Node-Red with SSL enabled.  I disabled SSL and used basic authentication and seem to be getting the responses expected from the input node now.  I was trying a lot of different things so not 100% sure that was the cause.  

Once again, I need to confirm but it might be a few days (possibly weekend) before I can.  You may know of a reason that this might have been causing the issue but I have no clue why it would have.

**Comment by hardillb** [comment]
Ahh, yes that will be the case. The way the input node works is using UPnP subscriptions that work by sending the device a URL to make HTTP POST requests back to when things change.

Due to how Node-RED works everything uses the same HTTP server, so if you enable HTTPS then the POST from the device won't work because it can't make HTTPS requests.

**Comment by damiene77** [comment]
Well, calling this one then.  Case closed.
Thanks for the help.

I noticed that it was brought up recently (on your blog maybe) that the lookup node does not pull in power data from Insights.  Is this something that might be added later?

Thanks again.

**Comment by hardillb** [comment]
It's been a long time since I last looked but if i remember correctly the WeMo Insight only generates events when the power usage crosses a pre-set boundary (in both directions). I think you have to poll for general power usage figures.

I'll add it to my (long) list of things to do while on lock down, but happy to look at a pull request if you want to have a go. I have a bunch of blog posts from when I reverse engineered the control protocol here: https://www.hardill.me.uk/wordpress/tag/wemo/
