### ISSUE TITLE
node-red-node-sqlite - bullseye installation issue

### ISSUE THREAD

**Issue by anwarbashir** [node-red/node-red-nodes#905]
### Please tell us about your environment:

- [x] Node-RED version:
- [x] node.js version:
- [x] npm version:
- [x] Platform/OS:
- [ ] Browser:

**Comment by anwarbashir** [comment]
Node-RED 2.2.2
nodejs v14.19.1
npm 6.14.16
OS - Raspbian bullseye

npm install node-red-node-sqlite appears to work but then I get waiting for missing types to be registered - sqlite - sqlitedb

**Comment by hardillb** [comment]
- 32 or 64 bit Raspberry Pi OS?
- What is in the the logs when it fails to load the modules?
- Exactly where did you run the `npm install` command?
- what is the output if you run the following commands
    ```
    mkdir test
    cd test
    npm install sqlite3
    ```

**Comment by hardillb** [comment]
That wasn't what I asked. Please follow the steps I laid out in the last point and post the output as I need to see if the sqlite3 npm modules installs properly and builds it's native component.

You also haven't answered the questions about where you ran the initial `npm install node-red-node-sqlite` command or supplied the logs I asked for.

**Comment by anwarbashir** [comment]
Okay, I am just trying the instructions that you posted, I will let know know in the next few minutes. I am a newbie and because sqlite3 was installed and appears to be working I did not consider this might be causing the issue until now.

**Comment by anwarbashir** [comment]
I ran the npm node-red-node-sqlite from ./node-red

**Comment by anwarbashir** [comment]
While sqlite3 is installing its giving me lots of warnings 'this statement may fall through' and its taking a while on my RPi3 A+

**Comment by anwarbashir** [comment]
The command npm install sqlite3 as per your instruction locks up the RPi at line 197088. This was also happening when I tried to install npm install node-red-node-sqlite, so I now assume that this command tries to install sqlite3 and on my OS Bullseye it locks at this line. I have installed on previous OS versions so not sure why. I am unable to provide a log because the only way now is to reboot the Pi. Any ideas?

**Comment by hardillb** [comment]
Without the logs I really can't say.

Are you 100% sure it had totally hung and just was busy building the native part? Did you try to log in remotely via SSH? Also rather than power cycle just leave it be for several hours.

**Comment by anwarbashir** [comment]
I have left it a number of times, even overnight. I am sure that it just locks up. Did not try SSH, but keyboard etc does not respond.

**Comment by anwarbashir** [comment]
I implemented a workaround. I installed sqlite on RPi4 previously and it worked. So I took the microSD card from my RPi3 A+ and installed installed from RPi4. It worked. I then placed the microSD card back in my RPi3 A+ and checked and it worked. I have implemented a quick CRUD and all appears okay. Not a proper solution, but it point to an unsupported architecture issue? Much obliged to you for working with me on this.

**Comment by Zupayruna1** [comment]
When I try to install sudo npm install node-red-node-sqlite  --loglevel verbose  the error was (image):
![imagen](https://user-images.githubusercontent.com/45931451/188279911-a15074f2-dcb5-4486-b32a-ba3b0df4bcd0.png)

I'm using the Debian11.4 Bullseye IoT Image 2022-09-02, then I install without problems "npm install -g node-pre-gyp"  but the error repeat with "npm install node-red-node-sqlite  --loglevel verbose":

npm verb node v12.22.12
npm verb npm  v8.19.1
npm ERR! code 1
npm ERR! path /home/debian/node_modules/node-red-node-sqlite/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! internal/modules/cjs/loader.js:818
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'nopt'
npm ERR! Require stack:
npm ERR! - /home/debian/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
npm ERR! - /home/debian/node_modules/@mapbox/node-pre-gyp/lib/main.js
npm ERR! - /home/debian/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/home/debian/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:22:14)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/debian/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js',
npm ERR!     '/home/debian/node_modules/@mapbox/node-pre-gyp/lib/main.js',
npm ERR!     '/home/debian/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp'
npm ERR!   ]
npm ERR! }
npm verb exit 1
npm timing npm Completed in 68444ms
npm verb unfinished npm timer reify 1662222796263
npm verb unfinished npm timer reify:build 1662222854431
npm verb unfinished npm timer build 1662222854440
npm verb unfinished npm timer build:deps 1662222854445
npm verb unfinished npm timer build:run:install 1662222854811
npm verb unfinished npm timer build:run:install:node_modules/node-red-node-sqlite/node_modules/sqlite3 1662222854820
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-03T16_33_13_782Z-debug-0.log

**Comment by hardillb** [comment]
@Zupayruna1

First why are you running npm with sudo? (npm really doen't like running as root these days, it drops nearly all permissions as soon as possible.

 It looks like you are in the `debian` users home dir (which is probably not where you want to be either, by default node-red nodes should be installed in the Node-RED userDir which defaults to `~/.node-red` not the users home dir. Nodes should be installed as the user that will run Node-RED and that normally really shouldn't be root unless you are very aware of the security issues around that.


Next, is there a directory called `nopt` in `/home/debian/node_modules`?

Installing `node-pre-gyp` won't help because the build is using the scoped version of the package `@mapbox/node-pre-gyp` which is the much newer version.

The problem is with building the native component for the underlying sqlite3 node

**Comment by Zupayruna1** [comment]
> @Zupayruna1
> 
> First why are you running npm with sudo? (npm really doen't like running as root these days, it drops nearly all permissions as soon as possible.
 
because when I saw the logs I had problems with permission

> 
> It looks like you are in the `debian` users home dir (which is probably not where you want to be either, by default node-red nodes should be installed in the Node-RED userDir which defaults to `~/.node-red` not the users home dir. Nodes should be installed as the user that will run Node-RED and that normally really shouldn't be root unless you are very aware of the security issues around that.
Sure, but my Nodered came installed and only I need the system nodered for try with examples not for a business project. I'm beginner in node red

> 
> Next, is there a directory called `nopt` in `/home/debian/node_modules`?
no there is not
> 
> Installing `node-pre-gyp` won't help because the build is using the scoped version of the package `@mapbox/node-pre-gyp` which is the much newer version.
> 
> The problem is with building the native component for the underlying sqlite3 node

I tried with this https://github.com/mapbox/node-pre-gyp/issues/477   : -> 
sudo apt-get install -y build-essential python
npm install node-pre-gyp
npm install -g node-gyp

and I didnt have errors during installation  npm install node-red-node-sqlite --loglevel verbose 
But I can't see the node sqlite in nodered GUI 

I tried with ur code "npm install sqlite3" but the system error was:
![imagen](https://user-images.githubusercontent.com/45931451/188282205-957dfeb2-b807-49d7-9ae9-f1aa80302843.png)

**Comment by hardillb** [comment]
Because as I said, nodes need to be installed into the `/home/debian/.node-red` not `/home/debian`

**Comment by hardillb** [comment]
Sorry, re-reading that error in the new image (Please don't post images of text, post the text and use tripple back ticks to format it) you may have your Node-RED userDir set to `/var/lib/node-red/.node-red` which is strange and not something I would recommend because those paths again tend to need root access to write to.

If you still have problems you should probably post to the forum where somebody may have time to help you unpick it, but I'm going to close this issue as the OP is fixed and this is not an actual problem with the node, it is more to do with the state you've got your environment in.
