### ISSUE TITLE
SenseHat 1.0 with Node-Red / RPI4 "Disconnected"

### ISSUE THREAD

**Issue by dhanzseros** [node-red/node-red-nodes#958]
Hey,

I cannot use the Sense Hat node in Node-red. It shows always disconnected state. The SenseHat version is 1.0 (2015) with RPI4. It works with python perfectly (only color sensor is missing).

I have reinstalled the whole OS, Node-red, python, everything but the Sensehat node still  shows disconnected.

- [ ] Node-RED version: 3.02
- [ ] node.js version: 16.18
- [ ] npm version: 8.19.2
- [ ] Platform/OS: Raspbian OS
- [ ] Browser:

**Comment by juggledad** [comment]
Try installing Python 2. Python 3 changed some of the things that were being used in communicating between NR and the Pythoon code.  I did take a look, but not being a python programmer (and gramps duties) I never was able to come up with a solution. 

If anyone wants to try to fix the node's python code, I'll be happy to explain what I think the issue is.

**Comment by Nezakka** [comment]
Thank you p-luthi. I've been messing with this for over 6 hours.

**Comment by dceejay** [comment]
Hi @p-luthi , @Nezakka 
any chance either of you could try adding in just 
`RED.log.error("err: "+data+":");`
and reporting what the actual error it is failing on is... 
(as in I'm suprised that it is then continuing OK... so either we can tweak it to ignore that non-fatal error - or something else is up...)
Thanks

**Comment by sisomm** [comment]
Hi @dceejay I hade the same problem, commented out the SIGKILL and added the line you asked for. This was the output: 
27 Nov 22:26:19 - [warn] Encrypted credentials not found
27 Nov 22:26:19 - [info] Server now running at http://127.0.0.1:1880/
27 Nov 22:26:19 - [info] Starting flows
      pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python3 -u /home/pi/.node-red/node_modules/node-red-node-pi-sense-hat/sensehat.py
pam_unix(sudo:session): session opened for user root by (uid=0)
27 Nov 22:26:19 - [info] Started flows
27 Nov 22:26:19 - [info] [mqtt-broker:3a4d13cf.e1e27c] Connected to broker: mqtt://localhost:1883
27 Nov 22:26:19 - [error] err: WARNING:root:Failed to initialise TCS34725 colour sensor. (sensor not present)

**Comment by p-luthi** [comment]
Hi @dceejay 
Same issue as described by @sisomm :
28 Nov 10:32:25 - [info] Node-RED version: v3.0.2
28 Nov 10:32:25 - [info] Node.js  version: v16.18.1
28 Nov 10:32:25 - [info] Linux 5.10.103-v7l+ arm LE
28 Nov 10:32:26 - [info] Loading palette nodes
28 Nov 10:32:27 - [info] Dashboard version 3.2.0 started at /ui
28 Nov 10:32:28 - [info] Settings file  : /home/pi/.node-red/settings.js
28 Nov 10:32:28 - [info] Context store  : 'default' [module=memory]
28 Nov 10:32:28 - [info] User directory : /home/pi/.node-red
28 Nov 10:32:28 - [warn] Projects disabled : editorTheme.projects.enabled=false
28 Nov 10:32:28 - [info] Flows file     : /home/pi/.node-red/flows.json
28 Nov 10:32:28 - [warn] Encrypted credentials not found
28 Nov 10:32:28 - [info] Server now running at http://127.0.0.1:1880/
28 Nov 10:32:28 - [info] Starting flows
28 Nov 10:32:28 - [info] Started flows
28 Nov 10:32:28 - [error] err :WARNING:root:Failed to initialise TCS34725 colour sensor. (sensor not present) :
28 Nov 10:32:29 - [info] [debug:debug 1]
Apparently the problem comes from the detection of the color sensor of the sense hat (I have an old version - v1.0)...

**Comment by dceejay** [comment]
Great - thanks. So it is "only" a Warning - so yes we could try to ignore that :-)

**Comment by dceejay** [comment]
can someone please try the following to replace the logging above

```
                if (data.indexOf("WARNING") === 0) { 
                    if (data.indexOf("sensor not present") !== -1) { return; }
                    else { RED.log.warn(data); }
                }
                else {
                    hat.kill('SIGKILL');
                }
```

hopefully that will ignore colour sensor warning  - report other warnings (without killing it), and otherwise kill it.

**Comment by p-luthi** [comment]
Looks good, sense hat still connected without error :
28 Nov 12:35:09 - [info] Node-RED version: v3.0.2
28 Nov 12:35:09 - [info] Node.js  version: v16.18.1
28 Nov 12:35:09 - [info] Linux 5.10.103-v7l+ arm LE
28 Nov 12:35:10 - [info] Loading palette nodes
28 Nov 12:35:12 - [info] Dashboard version 3.2.0 started at /ui
28 Nov 12:35:12 - [info] Settings file  : /home/pi/.node-red/settings.js
28 Nov 12:35:12 - [info] Context store  : 'default' [module=memory]
28 Nov 12:35:12 - [info] User directory : /home/pi/.node-red
28 Nov 12:35:12 - [warn] Projects disabled : editorTheme.projects.enabled=false
28 Nov 12:35:12 - [info] Flows file     : /home/pi/.node-red/flows.json
28 Nov 12:35:12 - [warn] Encrypted credentials not found
28 Nov 12:35:12 - [info] Server now running at http://127.0.0.1:1880/
28 Nov 12:35:12 - [info] Starting flows
28 Nov 12:35:12 - [info] Started flows

**Comment by dceejay** [comment]
Now published as V 0.1.4
Many thanks for all your help

**Comment by sisomm** [comment]
Downloaded and deployed. It works. Well done!

**Comment by Nowjet** [comment]
Hello, 
I have the same Problem but with the V 0.1.4
already tried to comment the new lines of the version.
Tried several times removing and installing the node-red-node-pi-sense-hat module.

Hope you can help me.
Thanks in advance
